-- Firecrawl-researched France pass, 2026-08-26.
-- 1) Widens course_tee_holes.par AND course_holes.par to allow real par-6
--    holes (Belle Dune's 15th is a genuine signature par 6, confirmed via
--    TripAdvisor + the club's own site -- the original CHECK
--    (par BETWEEN 3 AND 5) on both tables wrongly excluded it; course_holes
--    needs the same widening because Belle Dune's Blanc tee is selected as
--    the "primary" tee for the single-value course_holes row below).
-- 2) Inserts two net-new courses: Belle Dune (Blanc + Jaune) and Golf du Champ de
--    Bataille (all 4 tees, men's + women's ratings for Jaune/Bleu/Rouge), sourced
--    from golfify.io and the official club scorecard respectively. Neither course
--    exists in the already-applied course_master_import migration.
-- Nothing existing is altered or removed.

ALTER TABLE course_tee_holes DROP CONSTRAINT IF EXISTS course_tee_holes_par_check;
ALTER TABLE course_tee_holes ADD CONSTRAINT course_tee_holes_par_check CHECK (par BETWEEN 3 AND 6);

ALTER TABLE course_holes DROP CONSTRAINT IF EXISTS course_holes_par_check;
ALTER TABLE course_holes ADD CONSTRAINT course_holes_par_check CHECK (par BETWEEN 3 AND 6);

INSERT INTO course_tees (course_name, tee_name, gender, par, total_distance, distance_unit, course_rating, slope_rating, source, rating_status, source_course_id) VALUES
('Belle Dune', 'Blanc', 'M', 73, 5868, 'yd', 73.1, 140, 'https://www.golfify.io/courses/golf-de-belle-dune', 'MERGED', 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 72, 5482, 'yd', 71.6, 125, 'https://www.golfify.io/courses/golf-de-belle-dune', 'MERGED', 'BELLE_DUNE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 72, 5993, 'yd', 72.3, 144, 'https://www.golf-champdebataille.com/carte-score', 'MERGED', 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 72, 5103, 'yd', 67.5, 138, 'https://www.golf-champdebataille.com/carte-score', 'MERGED', 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 72, 5103, 'yd', 72.8, 144, 'https://www.golf-champdebataille.com/carte-score', 'MERGED', 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 72, 5640, 'yd', 70.2, 141, 'https://www.golf-champdebataille.com/carte-score', 'MERGED', 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 72, 5640, 'yd', 76, 146, 'https://www.golf-champdebataille.com/carte-score', 'MERGED', 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 72, 4486, 'yd', 64.5, 129, 'https://www.golf-champdebataille.com/carte-score', 'MERGED', 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 72, 4486, 'yd', 69.4, 130, 'https://www.golf-champdebataille.com/carte-score', 'MERGED', 'GOLF_DU_CHAMP_DE_BATAILLE')
ON CONFLICT (course_name, tee_name, gender) DO NOTHING;

INSERT INTO course_tee_holes (course_name, tee_name, gender, hole_number, distance, par, stroke_index, source_course_id) VALUES
('Belle Dune', 'Blanc', 'M', 1, 349, 4, 12, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 2, 342, 4, 7, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 3, 144, 3, 18, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 4, 444, 5, 16, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 5, 387, 4, 9, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 6, 162, 3, 14, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 7, 371, 4, 5, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 8, 397, 4, 3, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 9, 297, 4, 11, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 10, 517, 5, 4, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 11, 367, 4, 6, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 12, 141, 3, 13, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 13, 449, 5, 2, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 14, 138, 3, 17, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 15, 352, 6, 1, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 16, 264, 4, 15, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 17, 348, 4, 8, 'BELLE_DUNE'),
('Belle Dune', 'Blanc', 'M', 18, 399, 4, 10, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 1, 328, 4, 12, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 2, 323, 4, 7, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 3, 126, 3, 18, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 4, 419, 5, 16, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 5, 349, 4, 9, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 6, 145, 3, 14, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 7, 352, 4, 5, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 8, 366, 4, 3, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 9, 279, 4, 11, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 10, 493, 5, 4, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 11, 350, 4, 6, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 12, 131, 3, 13, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 13, 441, 5, 2, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 14, 127, 3, 17, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 15, 330, 5, 1, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 16, 232, 4, 15, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 17, 323, 4, 8, 'BELLE_DUNE'),
('Belle Dune', 'Jaune', 'M', 18, 368, 4, 10, 'BELLE_DUNE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 1, 350, 4, 9, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 2, 157, 3, 16, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 3, 317, 4, 3, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 4, 502, 5, 1, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 5, 152, 3, 18, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 6, 320, 4, 17, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 7, 349, 4, 11, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 8, 455, 5, 4, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 9, 374, 4, 6, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 10, 467, 5, 12, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 11, 337, 4, 8, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 12, 174, 3, 14, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 13, 349, 4, 2, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 14, 350, 4, 13, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 15, 398, 4, 5, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 16, 457, 5, 10, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 17, 136, 3, 15, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Blanc', 'M', 18, 349, 4, 7, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 1, 297, 4, 9, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 2, 142, 3, 16, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 3, 267, 4, 3, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 4, 482, 5, 1, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 5, 114, 3, 18, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 6, 277, 4, 17, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 7, 232, 4, 11, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 8, 417, 5, 4, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 9, 274, 4, 6, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 10, 427, 5, 12, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 11, 294, 4, 8, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 12, 136, 3, 14, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 13, 285, 4, 2, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 14, 292, 4, 13, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 15, 364, 4, 5, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 16, 423, 5, 10, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 17, 121, 3, 15, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'M', 18, 259, 4, 7, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 1, 297, 4, 9, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 2, 142, 3, 16, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 3, 267, 4, 3, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 4, 482, 5, 1, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 5, 114, 3, 18, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 6, 277, 4, 17, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 7, 232, 4, 11, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 8, 417, 5, 4, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 9, 274, 4, 6, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 10, 427, 5, 12, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 11, 294, 4, 8, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 12, 136, 3, 14, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 13, 285, 4, 2, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 14, 292, 4, 13, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 15, 364, 4, 5, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 16, 423, 5, 10, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 17, 121, 3, 15, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Bleu', 'F', 18, 259, 4, 7, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 1, 332, 4, 9, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 2, 157, 3, 16, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 3, 285, 4, 3, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 4, 492, 5, 1, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 5, 134, 3, 18, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 6, 301, 4, 17, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 7, 304, 4, 11, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 8, 434, 5, 4, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 9, 358, 4, 6, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 10, 447, 5, 12, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 11, 304, 4, 8, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 12, 159, 3, 14, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 13, 343, 4, 2, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 14, 306, 4, 13, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 15, 374, 4, 5, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 16, 444, 5, 10, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 17, 131, 3, 15, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'M', 18, 335, 4, 7, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 1, 332, 4, 9, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 2, 157, 3, 16, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 3, 285, 4, 3, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 4, 492, 5, 1, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 5, 134, 3, 18, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 6, 301, 4, 17, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 7, 304, 4, 11, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 8, 434, 5, 4, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 9, 358, 4, 6, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 10, 447, 5, 12, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 11, 304, 4, 8, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 12, 159, 3, 14, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 13, 343, 4, 2, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 14, 306, 4, 13, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 15, 374, 4, 5, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 16, 444, 5, 10, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 17, 131, 3, 15, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Jaune', 'F', 18, 335, 4, 7, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 1, 261, 4, 9, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 2, 71, 3, 16, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 3, 189, 4, 3, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 4, 436, 5, 1, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 5, 102, 3, 18, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 6, 233, 4, 17, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 7, 232, 4, 11, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 8, 401, 5, 4, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 9, 267, 4, 6, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 10, 376, 5, 12, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 11, 285, 4, 8, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 12, 127, 3, 14, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 13, 248, 4, 2, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 14, 217, 4, 13, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 15, 304, 4, 5, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 16, 364, 5, 10, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 17, 121, 3, 15, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'M', 18, 252, 4, 7, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 1, 261, 4, 9, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 2, 71, 3, 16, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 3, 189, 4, 3, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 4, 436, 5, 1, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 5, 102, 3, 18, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 6, 233, 4, 17, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 7, 232, 4, 11, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 8, 401, 5, 4, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 9, 267, 4, 6, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 10, 376, 5, 12, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 11, 285, 4, 8, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 12, 127, 3, 14, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 13, 248, 4, 2, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 14, 217, 4, 13, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 15, 304, 4, 5, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 16, 364, 5, 10, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 17, 121, 3, 15, 'GOLF_DU_CHAMP_DE_BATAILLE'),
('Golf du Champ de Bataille', 'Rouge', 'F', 18, 252, 4, 7, 'GOLF_DU_CHAMP_DE_BATAILLE')
ON CONFLICT (course_name, tee_name, gender, hole_number) DO NOTHING;

INSERT INTO course_holes (course_name, hole_number, par, stroke_index, yardage) VALUES
('Belle Dune', 1, 4, 12, 349),
('Belle Dune', 2, 4, 7, 342),
('Belle Dune', 3, 3, 18, 144),
('Belle Dune', 4, 5, 16, 444),
('Belle Dune', 5, 4, 9, 387),
('Belle Dune', 6, 3, 14, 162),
('Belle Dune', 7, 4, 5, 371),
('Belle Dune', 8, 4, 3, 397),
('Belle Dune', 9, 4, 11, 297),
('Belle Dune', 10, 5, 4, 517),
('Belle Dune', 11, 4, 6, 367),
('Belle Dune', 12, 3, 13, 141),
('Belle Dune', 13, 5, 2, 449),
('Belle Dune', 14, 3, 17, 138),
('Belle Dune', 15, 6, 1, 352),
('Belle Dune', 16, 4, 15, 264),
('Belle Dune', 17, 4, 8, 348),
('Belle Dune', 18, 4, 10, 399),
('Golf du Champ de Bataille', 1, 4, 9, 350),
('Golf du Champ de Bataille', 2, 3, 16, 157),
('Golf du Champ de Bataille', 3, 4, 3, 317),
('Golf du Champ de Bataille', 4, 5, 1, 502),
('Golf du Champ de Bataille', 5, 3, 18, 152),
('Golf du Champ de Bataille', 6, 4, 17, 320),
('Golf du Champ de Bataille', 7, 4, 11, 349),
('Golf du Champ de Bataille', 8, 5, 4, 455),
('Golf du Champ de Bataille', 9, 4, 6, 374),
('Golf du Champ de Bataille', 10, 5, 12, 467),
('Golf du Champ de Bataille', 11, 4, 8, 337),
('Golf du Champ de Bataille', 12, 3, 14, 174),
('Golf du Champ de Bataille', 13, 4, 2, 349),
('Golf du Champ de Bataille', 14, 4, 13, 350),
('Golf du Champ de Bataille', 15, 4, 5, 398),
('Golf du Champ de Bataille', 16, 5, 10, 457),
('Golf du Champ de Bataille', 17, 3, 15, 136),
('Golf du Champ de Bataille', 18, 4, 7, 349)
ON CONFLICT (course_name, hole_number) DO NOTHING;
