-- Firecrawl-researched France pass, 2026-08-26.
-- 1) Widens course_tee_holes.par to allow real par-6 holes (Belle Dune's 15th is
--    a genuine signature par 6, confirmed via TripAdvisor + the club's own site --
--    the original CHECK (par BETWEEN 3 AND 5) wrongly excluded it).
-- 2) Inserts two net-new courses: Belle Dune (Blanc + Jaune) and Golf du Champ de
--    Bataille (all 4 tees, men's + women's ratings for Jaune/Bleu/Rouge), sourced
--    from golfify.io and the official club scorecard respectively. Neither course
--    exists in the already-applied course_master_import migration.
-- Nothing existing is altered or removed.

ALTER TABLE course_tee_holes DROP CONSTRAINT IF EXISTS course_tee_holes_par_check;
ALTER TABLE course_tee_holes ADD CONSTRAINT course_tee_holes_par_check CHECK (par BETWEEN 3 AND 6);

INSERT INTO course_tees (course_name, tee_name, gender, par, total_distance, distance_unit, course_rating, slope_rating, source, rating_status, source_course_id) VALUES
('Bondues - Trent Jones', 'Blue', 'M', 72, 5507, 'yd', 67.7, 123, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 72, 4986, 'yd', 65.3, 119, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 72, 5977, 'yd', 69.8, 128, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'BONDUES_TRENT_JONES'),
('Château de Taulane', 'Blue', 'M', 72, 5850, 'yd', 74.1, 127, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 72, 5357, 'yd', 72.4, 124, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 72, 6756, 'yd', 74.1, 134, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 72, 6263, 'yd', 71.8, 131, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'CH_TEAU_DE_TAULANE'),
('La Boulie - La Forêt', 'Blue', 'M', 72, 5857, 'yd', 69.7, 115, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 72, 5617, 'yd', 73.8, 124, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 72, 6658, 'yd', 73.1, 127, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 72, 6433, 'yd', 72.3, 120, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Vallée', 'Blue', 'M', 72, 5678, 'yd', 68.7, 124, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 72, 5505, 'yd', 72.7, 133, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 72, 6474, 'yd', 72, 135, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 72, 6204, 'yd', 71, 129, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LA_BOULIE_LA_VALL_E'),
('Le Kempferhof', 'Blue', 'M', 72, 5429, 'yd', 67.2, 127, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 72, 4898, 'yd', 64.6, 122, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 72, 6549, 'yd', 72.2, 139, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 72, 6045, 'yd', 69.8, 132, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LE_KEMPFERHOF'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 72, 6575, 'yd', 75.5, 140, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 72, 5306, 'yd', 68.7, 123, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 72, 4999, 'yd', 67.1, 120, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 72, 6159, 'yd', 73, 134, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 72, 5851, 'yd', 71.3, 129, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 71, 5764, 'yd', 73.3, 137, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 71, 5441, 'yd', 71.5, 131, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 71, 6524, 'yd', 71.1, 138, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 71, 6168, 'yd', 69.7, 131, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Vidauban Golf Club', 'Black', 'M', 72, 6477, 'yd', 73.8, 141, 'https://www.golfpass.com (course scorecard-and-layout page)', 'VERIFIED', 'VIDAUBAN_GOLF_CLUB')
ON CONFLICT (course_name, tee_name, gender) DO NOTHING;

INSERT INTO course_tee_holes (course_name, tee_name, gender, hole_number, distance, par, stroke_index, source_course_id) VALUES
('Bondues - Trent Jones', 'Blue', 'M', 1, 448, 5, 7, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 2, 143, 3, 11, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 3, 265, 4, 15, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 4, 422, 5, 9, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 5, 351, 4, 1, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 6, 90, 3, 17, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 7, 377, 4, 3, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 8, 364, 4, 5, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 9, 440, 5, 13, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 10, 484, 5, 2, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 11, 163, 3, 8, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 12, 320, 4, 10, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 13, 306, 4, 16, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 14, 138, 3, 18, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 15, 407, 5, 14, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 16, 128, 3, 12, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 17, 283, 4, 6, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Blue', 'M', 18, 378, 4, 4, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 1, 417, 5, 7, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 2, 120, 3, 11, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 3, 246, 4, 15, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 4, 407, 5, 9, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 5, 312, 4, 1, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 6, 87, 3, 17, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 7, 340, 4, 3, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 8, 312, 4, 5, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 9, 416, 5, 13, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 10, 434, 5, 2, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 11, 132, 3, 8, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 12, 279, 4, 10, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 13, 262, 4, 16, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 14, 110, 3, 18, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 15, 392, 5, 14, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 16, 101, 3, 12, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 17, 252, 4, 6, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Red', 'M', 18, 367, 4, 4, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 1, 486, 5, 7, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 2, 160, 3, 11, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 3, 289, 4, 15, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 4, 457, 5, 9, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 5, 379, 4, 1, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 6, 122, 3, 17, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 7, 396, 4, 3, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 8, 385, 4, 5, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 9, 457, 5, 13, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 10, 495, 5, 2, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 11, 182, 3, 8, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 12, 357, 4, 10, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 13, 338, 4, 16, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 14, 152, 3, 18, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 15, 439, 5, 14, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 16, 152, 3, 12, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 17, 336, 4, 6, 'BONDUES_TRENT_JONES'),
('Bondues - Trent Jones', 'Yellow', 'M', 18, 395, 4, 4, 'BONDUES_TRENT_JONES'),
('Château de Taulane', 'Blue', 'M', 1, 344, 4, 7, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 2, 130, 3, 17, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 3, 444, 5, 13, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 4, 349, 4, 3, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 5, 464, 5, 5, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 6, 377, 4, 11, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 7, 308, 4, 9, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 8, 132, 3, 15, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 9, 379, 4, 1, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 10, 301, 4, 12, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 11, 351, 4, 4, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 12, 171, 3, 8, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 13, 519, 5, 6, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 14, 336, 4, 2, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 15, 385, 4, 14, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 16, 247, 4, 18, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 17, 159, 3, 16, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Blue', 'M', 18, 454, 5, 10, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 1, 315, 4, 7, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 2, 124, 3, 17, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 3, 414, 5, 13, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 4, 334, 4, 3, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 5, 427, 5, 5, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 6, 364, 4, 11, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 7, 277, 4, 9, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 8, 110, 3, 15, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 9, 367, 4, 1, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 10, 257, 4, 12, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 11, 326, 4, 4, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 12, 149, 3, 8, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 13, 462, 5, 6, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 14, 327, 4, 2, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 15, 332, 4, 14, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 16, 221, 4, 18, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 17, 135, 3, 16, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Red', 'M', 18, 416, 5, 10, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 1, 392, 4, 7, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 2, 171, 3, 17, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 3, 488, 5, 13, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 4, 407, 4, 3, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 5, 512, 5, 5, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 6, 409, 4, 11, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 7, 354, 4, 9, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 8, 168, 3, 15, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 9, 433, 4, 1, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 10, 363, 4, 12, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 11, 413, 4, 4, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 12, 201, 3, 8, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 13, 589, 5, 6, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 14, 384, 4, 2, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 15, 434, 4, 14, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 16, 290, 4, 18, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 17, 189, 3, 16, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'White', 'M', 18, 559, 5, 10, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 1, 367, 4, 7, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 2, 153, 3, 17, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 3, 488, 5, 13, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 4, 367, 4, 3, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 5, 492, 5, 5, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 6, 390, 4, 11, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 7, 322, 4, 9, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 8, 144, 3, 15, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 9, 406, 4, 1, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 10, 343, 4, 12, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 11, 371, 4, 4, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 12, 178, 3, 8, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 13, 544, 5, 6, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 14, 346, 4, 2, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 15, 408, 4, 14, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 16, 262, 4, 18, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 17, 167, 3, 16, 'CH_TEAU_DE_TAULANE'),
('Château de Taulane', 'Yellow', 'M', 18, 515, 5, 10, 'CH_TEAU_DE_TAULANE'),
('La Boulie - La Forêt', 'Blue', 'M', 1, 369, 4, 10, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 2, 122, 3, 2, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 3, 460, 5, 18, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 4, 379, 4, 8, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 5, 435, 5, 16, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 6, 315, 4, 14, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 7, 352, 4, 4, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 8, 318, 4, 12, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 9, 167, 3, 6, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 10, 527, 5, 9, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 11, 163, 3, 1, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 12, 363, 4, 17, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 13, 130, 3, 7, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 14, 488, 5, 15, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 15, 392, 4, 13, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 16, 344, 4, 3, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 17, 290, 4, 11, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Blue', 'M', 18, 243, 4, 5, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 1, 369, 4, 10, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 2, 118, 3, 2, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 3, 452, 5, 18, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 4, 379, 4, 8, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 5, 398, 5, 16, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 6, 315, 4, 14, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 7, 322, 4, 4, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 8, 314, 4, 12, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 9, 161, 3, 6, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 10, 499, 5, 9, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 11, 130, 3, 1, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 12, 336, 4, 17, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 13, 122, 3, 7, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 14, 456, 5, 15, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 15, 369, 4, 13, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 16, 344, 4, 3, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 17, 290, 4, 11, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Red', 'M', 18, 243, 4, 5, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 1, 369, 4, 10, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 2, 133, 3, 2, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 3, 484, 5, 18, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 4, 462, 4, 8, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 5, 466, 5, 16, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 6, 365, 4, 14, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 7, 434, 4, 4, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 8, 379, 4, 12, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 9, 182, 3, 6, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 10, 581, 5, 9, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 11, 182, 3, 1, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 12, 422, 4, 17, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 13, 156, 3, 7, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 14, 513, 5, 15, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 15, 416, 4, 13, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 16, 404, 4, 3, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 17, 343, 4, 11, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'White', 'M', 18, 367, 4, 5, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 1, 369, 4, 10, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 2, 128, 3, 2, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 3, 475, 5, 18, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 4, 441, 4, 8, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 5, 451, 5, 16, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 6, 357, 4, 14, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 7, 419, 4, 4, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 8, 357, 4, 12, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 9, 174, 3, 6, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 10, 557, 5, 9, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 11, 173, 3, 1, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 12, 399, 4, 17, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 13, 147, 3, 7, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 14, 502, 5, 15, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 15, 405, 4, 13, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 16, 392, 4, 3, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 17, 330, 4, 11, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Forêt', 'Yellow', 'M', 18, 357, 4, 5, 'LA_BOULIE_LA_FOR_T'),
('La Boulie - La Vallée', 'Blue', 'M', 1, 365, 4, 5, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 2, 400, 4, 1, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 3, 144, 3, 9, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 4, 402, 5, 17, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 5, 365, 4, 3, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 6, 311, 4, 11, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 7, 155, 3, 7, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 8, 475, 5, 13, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 9, 264, 4, 15, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 10, 168, 3, 6, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 11, 444, 5, 14, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 12, 318, 4, 12, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 13, 124, 3, 4, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 14, 351, 4, 8, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 15, 165, 3, 10, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 16, 393, 4, 2, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 17, 453, 5, 16, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Blue', 'M', 18, 381, 5, 18, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 1, 351, 4, 5, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 2, 392, 4, 1, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 3, 135, 3, 9, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 4, 402, 5, 17, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 5, 365, 4, 3, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 6, 302, 4, 11, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 7, 144, 3, 7, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 8, 439, 5, 13, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 9, 247, 4, 15, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 10, 168, 3, 6, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 11, 440, 5, 14, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 12, 303, 4, 12, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 13, 124, 3, 4, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 14, 342, 4, 8, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 15, 155, 3, 10, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 16, 376, 4, 2, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 17, 439, 5, 16, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Red', 'M', 18, 381, 5, 18, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 1, 398, 4, 5, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 2, 445, 4, 1, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 3, 164, 3, 9, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 4, 514, 5, 17, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 5, 463, 4, 3, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 6, 360, 4, 11, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 7, 177, 3, 7, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 8, 503, 5, 13, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 9, 306, 4, 15, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 10, 210, 3, 6, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 11, 499, 5, 14, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 12, 335, 4, 12, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 13, 173, 3, 4, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 14, 404, 4, 8, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 15, 187, 3, 10, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 16, 422, 4, 2, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 17, 474, 5, 16, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'White', 'M', 18, 440, 5, 18, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 1, 382, 4, 5, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 2, 427, 4, 1, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 3, 156, 3, 9, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 4, 487, 5, 17, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 5, 418, 4, 3, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 6, 338, 4, 11, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 7, 172, 3, 7, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 8, 497, 5, 13, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 9, 300, 4, 15, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 10, 187, 3, 6, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 11, 489, 5, 14, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 12, 327, 4, 12, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 13, 163, 3, 4, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 14, 396, 4, 8, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 15, 171, 3, 10, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 16, 406, 4, 2, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 17, 474, 5, 16, 'LA_BOULIE_LA_VALL_E'),
('La Boulie - La Vallée', 'Yellow', 'M', 18, 414, 5, 18, 'LA_BOULIE_LA_VALL_E'),
('Le Kempferhof', 'Blue', 'M', 1, 363, 4, 9, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 2, 480, 5, 1, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 3, 336, 4, 15, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 4, 452, 5, 5, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 5, 131, 3, 17, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 6, 249, 4, 3, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 7, 121, 3, 11, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 8, 439, 5, 7, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 9, 150, 3, 13, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 10, 250, 4, 2, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 11, 449, 5, 6, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 12, 318, 4, 4, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 13, 360, 4, 10, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 14, 147, 3, 14, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 15, 471, 5, 12, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 16, 256, 4, 16, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 17, 131, 3, 18, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Blue', 'M', 18, 326, 4, 8, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 1, 296, 4, 9, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 2, 435, 5, 1, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 3, 309, 4, 15, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 4, 436, 5, 5, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 5, 110, 3, 17, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 6, 268, 4, 3, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 7, 113, 3, 11, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 8, 421, 5, 7, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 9, 108, 3, 13, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 10, 230, 4, 2, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 11, 384, 5, 6, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 12, 277, 4, 4, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 13, 312, 4, 10, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 14, 132, 3, 14, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 15, 440, 5, 12, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 16, 229, 4, 16, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 17, 102, 3, 18, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Red', 'M', 18, 296, 4, 8, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 1, 419, 4, 9, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 2, 551, 5, 1, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 3, 376, 4, 15, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 4, 497, 5, 5, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 5, 178, 3, 17, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 6, 384, 4, 3, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 7, 165, 3, 11, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 8, 521, 5, 7, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 9, 177, 3, 13, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 10, 314, 4, 2, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 11, 506, 5, 6, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 12, 393, 4, 4, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 13, 420, 4, 10, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 14, 190, 3, 14, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 15, 558, 5, 12, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 16, 330, 4, 16, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 17, 168, 3, 18, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'White', 'M', 18, 402, 4, 8, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 1, 390, 4, 9, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 2, 517, 5, 1, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 3, 361, 4, 15, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 4, 472, 5, 5, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 5, 148, 3, 17, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 6, 351, 4, 3, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 7, 143, 3, 11, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 8, 492, 5, 7, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 9, 164, 3, 13, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 10, 285, 4, 2, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 11, 479, 5, 6, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 12, 360, 4, 4, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 13, 392, 4, 10, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 14, 164, 3, 14, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 15, 511, 5, 12, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 16, 297, 4, 16, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 17, 150, 3, 18, 'LE_KEMPFERHOF'),
('Le Kempferhof', 'Yellow', 'M', 18, 369, 4, 8, 'LE_KEMPFERHOF'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 1, 415, 4, 3, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 2, 526, 5, 17, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 3, 340, 4, 9, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 4, 162, 3, 11, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 5, 515, 5, 7, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 6, 389, 4, 1, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 7, 358, 4, 13, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 8, 178, 3, 15, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 9, 394, 4, 5, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 10, 388, 4, 16, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 11, 382, 4, 12, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 12, 395, 4, 2, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 13, 383, 4, 4, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 14, 179, 3, 14, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 15, 530, 5, 8, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 16, 387, 4, 10, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 17, 183, 3, 6, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Black', 'M', 18, 471, 5, 18, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 1, 283, 4, 3, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 2, 437, 5, 17, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 3, 275, 4, 9, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 4, 114, 3, 11, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 5, 437, 5, 7, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 6, 325, 4, 1, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 7, 266, 4, 13, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 8, 144, 3, 15, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 9, 315, 4, 5, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 10, 316, 4, 16, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 11, 315, 4, 12, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 12, 320, 4, 2, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 13, 324, 4, 4, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 14, 133, 3, 14, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 15, 448, 5, 8, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 16, 297, 4, 10, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 17, 148, 3, 6, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Blue', 'M', 18, 409, 5, 18, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 1, 272, 4, 3, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 2, 405, 5, 17, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 3, 263, 4, 9, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 4, 109, 3, 11, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 5, 410, 5, 7, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 6, 308, 4, 1, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 7, 261, 4, 13, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 8, 132, 3, 15, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 9, 300, 4, 5, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 10, 305, 4, 16, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 11, 307, 4, 12, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 12, 315, 4, 2, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 13, 294, 4, 4, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 14, 114, 3, 14, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 15, 416, 5, 8, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 16, 274, 4, 10, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 17, 136, 3, 6, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Red', 'M', 18, 378, 5, 18, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 1, 357, 4, 3, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 2, 493, 5, 17, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 3, 331, 4, 9, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 4, 155, 3, 11, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 5, 490, 5, 7, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 6, 365, 4, 1, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 7, 316, 4, 13, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 8, 166, 3, 15, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 9, 364, 4, 5, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 10, 374, 4, 16, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 11, 374, 4, 12, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 12, 358, 4, 2, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 13, 362, 4, 4, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 14, 166, 3, 14, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 15, 502, 5, 8, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 16, 345, 4, 10, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 17, 178, 3, 6, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'White', 'M', 18, 463, 5, 18, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 1, 339, 4, 3, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 2, 460, 5, 17, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 3, 315, 4, 9, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 4, 145, 3, 11, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 5, 471, 5, 7, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 6, 355, 4, 1, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 7, 312, 4, 13, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 8, 156, 3, 15, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 9, 352, 4, 5, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 10, 356, 4, 16, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 11, 356, 4, 12, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 12, 344, 4, 2, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 13, 357, 4, 4, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 14, 137, 3, 14, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 15, 495, 5, 8, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 16, 323, 4, 10, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 17, 160, 3, 6, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Lyon Golf Club - Les Sangliers', 'Yellow', 'M', 18, 418, 5, 18, 'LYON_GOLF_CLUB_LES_SANGLIERS'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 1, 386, 4, 3, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 2, 362, 4, 7, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 3, 471, 5, 13, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 4, 320, 4, 11, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 5, 339, 4, 9, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 6, 141, 3, 15, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 7, 361, 4, 1, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 8, 131, 3, 17, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 9, 372, 4, 5, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 10, 394, 4, 2, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 11, 147, 3, 10, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 12, 335, 4, 6, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 13, 160, 3, 8, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 14, 278, 4, 14, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 15, 459, 5, 16, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 16, 273, 4, 18, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 17, 468, 5, 12, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Blue', 'M', 18, 367, 4, 4, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 1, 379, 4, 3, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 2, 351, 4, 7, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 3, 441, 5, 13, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 4, 292, 4, 11, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 5, 328, 4, 9, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 6, 132, 3, 15, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 7, 346, 4, 1, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 8, 118, 3, 17, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 9, 363, 4, 5, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 10, 348, 4, 2, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 11, 147, 3, 10, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 12, 322, 4, 6, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 13, 153, 3, 8, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 14, 274, 4, 14, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 15, 381, 5, 16, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 16, 260, 4, 18, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 17, 449, 5, 12, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Red', 'M', 18, 357, 4, 4, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 1, 441, 4, 3, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 2, 453, 4, 7, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 3, 542, 5, 13, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 4, 362, 4, 11, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 5, 383, 4, 9, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 6, 149, 3, 15, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 7, 389, 4, 1, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 8, 148, 3, 17, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 9, 424, 4, 5, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 10, 451, 4, 2, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 11, 155, 3, 10, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 12, 420, 4, 6, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 13, 175, 3, 8, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 14, 309, 4, 14, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 15, 494, 5, 16, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 16, 317, 4, 18, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 17, 501, 5, 12, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'White', 'M', 18, 411, 4, 4, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 1, 424, 4, 3, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 2, 395, 4, 7, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 3, 511, 5, 13, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 4, 346, 4, 11, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 5, 361, 4, 9, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 6, 149, 3, 15, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 7, 373, 4, 1, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 8, 148, 3, 17, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 9, 405, 4, 5, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 10, 416, 4, 2, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 11, 155, 3, 10, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 12, 372, 4, 6, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 13, 168, 3, 8, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 14, 297, 4, 14, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 15, 469, 5, 16, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 16, 287, 4, 18, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 17, 487, 5, 12, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Saint-Cloud Golf Club - Vert', 'Yellow', 'M', 18, 405, 4, 4, 'SAINT_CLOUD_GOLF_CLUB_VERT'),
('Vidauban Golf Club', 'Black', 'M', 1, 402, 4, 5, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 2, 332, 4, 13, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 3, 534, 5, 3, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 4, 169, 3, 15, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 5, 371, 4, 9, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 6, 164, 3, 17, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 7, 332, 4, 11, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 8, 458, 5, 7, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 9, 397, 4, 1, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 10, 360, 4, 12, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 11, 169, 3, 18, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 12, 532, 5, 8, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 13, 409, 4, 2, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 14, 531, 5, 4, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 15, 396, 4, 10, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 16, 181, 3, 16, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 17, 386, 4, 6, 'VIDAUBAN_GOLF_CLUB'),
('Vidauban Golf Club', 'Black', 'M', 18, 354, 4, 14, 'VIDAUBAN_GOLF_CLUB')
ON CONFLICT (course_name, tee_name, gender, hole_number) DO NOTHING;

INSERT INTO course_holes (course_name, hole_number, par, stroke_index, yardage) VALUES
('Bondues - Trent Jones', 1, 5, 7, 448),
('Bondues - Trent Jones', 2, 3, 11, 143),
('Bondues - Trent Jones', 3, 4, 15, 265),
('Bondues - Trent Jones', 4, 5, 9, 422),
('Bondues - Trent Jones', 5, 4, 1, 351),
('Bondues - Trent Jones', 6, 3, 17, 90),
('Bondues - Trent Jones', 7, 4, 3, 377),
('Bondues - Trent Jones', 8, 4, 5, 364),
('Bondues - Trent Jones', 9, 5, 13, 440),
('Bondues - Trent Jones', 10, 5, 2, 484),
('Bondues - Trent Jones', 11, 3, 8, 163),
('Bondues - Trent Jones', 12, 4, 10, 320),
('Bondues - Trent Jones', 13, 4, 16, 306),
('Bondues - Trent Jones', 14, 3, 18, 138),
('Bondues - Trent Jones', 15, 5, 14, 407),
('Bondues - Trent Jones', 16, 3, 12, 128),
('Bondues - Trent Jones', 17, 4, 6, 283),
('Bondues - Trent Jones', 18, 4, 4, 378),
('Château de Taulane', 1, 4, 7, 344),
('Château de Taulane', 2, 3, 17, 130),
('Château de Taulane', 3, 5, 13, 444),
('Château de Taulane', 4, 4, 3, 349),
('Château de Taulane', 5, 5, 5, 464),
('Château de Taulane', 6, 4, 11, 377),
('Château de Taulane', 7, 4, 9, 308),
('Château de Taulane', 8, 3, 15, 132),
('Château de Taulane', 9, 4, 1, 379),
('Château de Taulane', 10, 4, 12, 301),
('Château de Taulane', 11, 4, 4, 351),
('Château de Taulane', 12, 3, 8, 171),
('Château de Taulane', 13, 5, 6, 519),
('Château de Taulane', 14, 4, 2, 336),
('Château de Taulane', 15, 4, 14, 385),
('Château de Taulane', 16, 4, 18, 247),
('Château de Taulane', 17, 3, 16, 159),
('Château de Taulane', 18, 5, 10, 454),
('La Boulie - La Forêt', 1, 4, 10, 369),
('La Boulie - La Forêt', 2, 3, 2, 122),
('La Boulie - La Forêt', 3, 5, 18, 460),
('La Boulie - La Forêt', 4, 4, 8, 379),
('La Boulie - La Forêt', 5, 5, 16, 435),
('La Boulie - La Forêt', 6, 4, 14, 315),
('La Boulie - La Forêt', 7, 4, 4, 352),
('La Boulie - La Forêt', 8, 4, 12, 318),
('La Boulie - La Forêt', 9, 3, 6, 167),
('La Boulie - La Forêt', 10, 5, 9, 527),
('La Boulie - La Forêt', 11, 3, 1, 163),
('La Boulie - La Forêt', 12, 4, 17, 363),
('La Boulie - La Forêt', 13, 3, 7, 130),
('La Boulie - La Forêt', 14, 5, 15, 488),
('La Boulie - La Forêt', 15, 4, 13, 392),
('La Boulie - La Forêt', 16, 4, 3, 344),
('La Boulie - La Forêt', 17, 4, 11, 290),
('La Boulie - La Forêt', 18, 4, 5, 243),
('La Boulie - La Vallée', 1, 4, 5, 365),
('La Boulie - La Vallée', 2, 4, 1, 400),
('La Boulie - La Vallée', 3, 3, 9, 144),
('La Boulie - La Vallée', 4, 5, 17, 402),
('La Boulie - La Vallée', 5, 4, 3, 365),
('La Boulie - La Vallée', 6, 4, 11, 311),
('La Boulie - La Vallée', 7, 3, 7, 155),
('La Boulie - La Vallée', 8, 5, 13, 475),
('La Boulie - La Vallée', 9, 4, 15, 264),
('La Boulie - La Vallée', 10, 3, 6, 168),
('La Boulie - La Vallée', 11, 5, 14, 444),
('La Boulie - La Vallée', 12, 4, 12, 318),
('La Boulie - La Vallée', 13, 3, 4, 124),
('La Boulie - La Vallée', 14, 4, 8, 351),
('La Boulie - La Vallée', 15, 3, 10, 165),
('La Boulie - La Vallée', 16, 4, 2, 393),
('La Boulie - La Vallée', 17, 5, 16, 453),
('La Boulie - La Vallée', 18, 5, 18, 381),
('Le Kempferhof', 1, 4, 9, 363),
('Le Kempferhof', 2, 5, 1, 480),
('Le Kempferhof', 3, 4, 15, 336),
('Le Kempferhof', 4, 5, 5, 452),
('Le Kempferhof', 5, 3, 17, 131),
('Le Kempferhof', 6, 4, 3, 249),
('Le Kempferhof', 7, 3, 11, 121),
('Le Kempferhof', 8, 5, 7, 439),
('Le Kempferhof', 9, 3, 13, 150),
('Le Kempferhof', 10, 4, 2, 250),
('Le Kempferhof', 11, 5, 6, 449),
('Le Kempferhof', 12, 4, 4, 318),
('Le Kempferhof', 13, 4, 10, 360),
('Le Kempferhof', 14, 3, 14, 147),
('Le Kempferhof', 15, 5, 12, 471),
('Le Kempferhof', 16, 4, 16, 256),
('Le Kempferhof', 17, 3, 18, 131),
('Le Kempferhof', 18, 4, 8, 326),
('Lyon Golf Club - Les Sangliers', 1, 4, 3, 415),
('Lyon Golf Club - Les Sangliers', 2, 5, 17, 526),
('Lyon Golf Club - Les Sangliers', 3, 4, 9, 340),
('Lyon Golf Club - Les Sangliers', 4, 3, 11, 162),
('Lyon Golf Club - Les Sangliers', 5, 5, 7, 515),
('Lyon Golf Club - Les Sangliers', 6, 4, 1, 389),
('Lyon Golf Club - Les Sangliers', 7, 4, 13, 358),
('Lyon Golf Club - Les Sangliers', 8, 3, 15, 178),
('Lyon Golf Club - Les Sangliers', 9, 4, 5, 394),
('Lyon Golf Club - Les Sangliers', 10, 4, 16, 388),
('Lyon Golf Club - Les Sangliers', 11, 4, 12, 382),
('Lyon Golf Club - Les Sangliers', 12, 4, 2, 395),
('Lyon Golf Club - Les Sangliers', 13, 4, 4, 383),
('Lyon Golf Club - Les Sangliers', 14, 3, 14, 179),
('Lyon Golf Club - Les Sangliers', 15, 5, 8, 530),
('Lyon Golf Club - Les Sangliers', 16, 4, 10, 387),
('Lyon Golf Club - Les Sangliers', 17, 3, 6, 183),
('Lyon Golf Club - Les Sangliers', 18, 5, 18, 471),
('Saint-Cloud Golf Club - Vert', 1, 4, 3, 386),
('Saint-Cloud Golf Club - Vert', 2, 4, 7, 362),
('Saint-Cloud Golf Club - Vert', 3, 5, 13, 471),
('Saint-Cloud Golf Club - Vert', 4, 4, 11, 320),
('Saint-Cloud Golf Club - Vert', 5, 4, 9, 339),
('Saint-Cloud Golf Club - Vert', 6, 3, 15, 141),
('Saint-Cloud Golf Club - Vert', 7, 4, 1, 361),
('Saint-Cloud Golf Club - Vert', 8, 3, 17, 131),
('Saint-Cloud Golf Club - Vert', 9, 4, 5, 372),
('Saint-Cloud Golf Club - Vert', 10, 4, 2, 394),
('Saint-Cloud Golf Club - Vert', 11, 3, 10, 147),
('Saint-Cloud Golf Club - Vert', 12, 4, 6, 335),
('Saint-Cloud Golf Club - Vert', 13, 3, 8, 160),
('Saint-Cloud Golf Club - Vert', 14, 4, 14, 278),
('Saint-Cloud Golf Club - Vert', 15, 5, 16, 459),
('Saint-Cloud Golf Club - Vert', 16, 4, 18, 273),
('Saint-Cloud Golf Club - Vert', 17, 5, 12, 468),
('Saint-Cloud Golf Club - Vert', 18, 4, 4, 367),
('Vidauban Golf Club', 1, 4, 5, 402),
('Vidauban Golf Club', 2, 4, 13, 332),
('Vidauban Golf Club', 3, 5, 3, 534),
('Vidauban Golf Club', 4, 3, 15, 169),
('Vidauban Golf Club', 5, 4, 9, 371),
('Vidauban Golf Club', 6, 3, 17, 164),
('Vidauban Golf Club', 7, 4, 11, 332),
('Vidauban Golf Club', 8, 5, 7, 458),
('Vidauban Golf Club', 9, 4, 1, 397),
('Vidauban Golf Club', 10, 4, 12, 360),
('Vidauban Golf Club', 11, 3, 18, 169),
('Vidauban Golf Club', 12, 5, 8, 532),
('Vidauban Golf Club', 13, 4, 2, 409),
('Vidauban Golf Club', 14, 5, 4, 531),
('Vidauban Golf Club', 15, 4, 10, 396),
('Vidauban Golf Club', 16, 3, 16, 181),
('Vidauban Golf Club', 17, 4, 6, 386),
('Vidauban Golf Club', 18, 4, 14, 354)
ON CONFLICT (course_name, hole_number) DO NOTHING;
