-- Real region/country per course, for the in-app region-tab picker.
-- Additive: courses.name is the same key already used across the app,
-- so nothing else changes. NULL region = not yet matched to the course
-- master import (shows under an "Other" tab in the picker).

ALTER TABLE courses ADD COLUMN IF NOT EXISTS region TEXT;

INSERT INTO courses (name, region) VALUES
('Barnehurst Golf Club', NULL),
('Dartford GC', NULL),
('Jandía Golf Course', NULL),
('Lullingstone Park Golf Club', NULL),
('North Foreland Golf Club', NULL),
('Praia D''El Rey', NULL),
('Prince''s Golf Club - Dunes', NULL),
('Prince''s Golf Club - Himalyas', NULL),
('Prince''s Golf Club - Shore', NULL),
('Prince''s Golf Club - Shore & Himalyas', NULL),
('The Melbourne Club At Brocket Hall', NULL),
('The Shire London Golf Club', NULL),
('Upchurch River Valley Golf Club', NULL),
('Aa Saint-Omer Golf Club (Du Val)', 'France'),
('Abama Golf', 'Spain'),
('Aberdovey Golf Club', 'Wales'),
('Addington Court Golf Club', 'England'),
('Álamos Golf Course', 'Portugal'),
('Alcaidesa Heathland', 'Spain'),
('Alferini', 'Spain'),
('Alhama Signature Golf', 'Spain'),
('Alicante Golf', 'Spain'),
('Aloha Golf Club', 'Spain'),
('Alsace Golf Links', 'France'),
('Alyth Golf Club', 'Scotland'),
('Amarilla Golf', 'Spain'),
('Amendoeira Golf Resort (Faldo)', 'Portugal'),
('Amendoeira Golf Resort (O''Connor Jnr.)', 'Portugal'),
('Andover Golf Club', 'England'),
('Anfi Tauro', 'Spain'),
('Anoreta', 'Spain'),
('Antalya Golf Club Pasha', 'Turkey'),
('Antalya Golf Club PGA Sultan', 'Turkey'),
('Archerfield - Dirleton Links', 'Scotland'),
('Archerfield - Fidra Links', 'Scotland'),
('Aroeira Golf Club (Aroeira II)', 'Portugal'),
('Aroeira Pines Classic', 'Portugal'),
('Ashburnham Golf Club', 'Wales'),
('Atalaya New', 'Spain'),
('Atalaya Old', 'Spain'),
('Auchterarder Golf Club', 'Scotland'),
('Avisford Park Golf Club', 'England'),
('Axis Ponte de Lima Golf Resort', 'Portugal'),
('Azeitão Golf', 'Portugal'),
('Badgemore Park Golf Club', 'England'),
('Ballards Gore Golf Club', 'England'),
('Ballybunion - Cashen', 'Ireland & Northern Ireland'),
('Ballybunion - Old', 'Ireland & Northern Ireland'),
('Ballyliffin - Glashedy', 'Ireland & Northern Ireland'),
('Ballyliffin - Old Links', 'Ireland & Northern Ireland'),
('Barbaroux', 'France'),
('Bay Hill Club & Lodge', 'Orlando / Central Florida'),
('Bearwood Lakes Golf Club', 'England'),
('Belas Clube de Campo', 'Portugal'),
('Belton Woods - Lakes', 'England'),
('Belton Woods - Woodside', 'England'),
('Benamor Golf', 'Portugal'),
('Bexleyheath Golf Club', 'England'),
('Biarritz Le Phare', 'France'),
('Bigbury Golf Club', 'England'),
('Birchwood Park Golf Centre - Birchwood Park Golf Club', 'England'),
('Blackmoor Golf Club', 'England'),
('Blairgowrie - Lansdowne', 'Scotland'),
('Blairgowrie - Rosemount', 'Scotland'),
('Bletchingley Golf Club', 'England'),
('Boat of Garten Golf Club', 'Scotland'),
('Boavista Golf & Spa Resort', 'Portugal'),
('Bonalba Golf', 'Spain'),
('Bovey Castle on Dartmoor National Park', 'England'),
('Bowood Park Hotel and Golf Club', 'England'),
('Brittas Bay', 'Ireland & Northern Ireland'),
('Brokenhurst Manor Golf Club', 'England'),
('Broome Park Golf Club', 'England'),
('Brora Golf Club', 'Scotland'),
('Bruntsfield Links Golfing Society', 'Scotland'),
('Bude & North Cornwall Golf Club', 'England'),
('Buenavista Golf', 'Spain'),
('Burhill Golf Club - New Course', 'England'),
('Cabopino', 'Spain'),
('Cabot Bordeaux (Châteaux)', 'France'),
('Cabot Bordeaux (Les Vignes)', 'France'),
('Calanova', 'Spain'),
('Camberley Heath Golf Club', 'England'),
('Camiral Resort (Stadium)', 'Spain'),
('Camiral Resort (Tour)', 'Spain'),
('Campoamor', 'Spain'),
('Cams Hall Golf Club', 'England'),
('Cams Hall Golf Club - Creek Course', 'England'),
('Cape Cornwall Golf and Country Club', 'England'),
('Carden Park - Cheshire', 'England'),
('Carden Park - Nicklaus', 'England'),
('Cardrona Championship Course', 'Scotland'),
('Carlyon Bay Golf Club', 'England'),
('Carne', 'Ireland & Northern Ireland'),
('Carnoustie - Buddon', 'Scotland'),
('Carnoustie - Burnside', 'Scotland'),
('Carnoustie - Championship', 'Scotland'),
('Carswell Golf Club', 'England'),
('Carton House - Montgomerie', 'Ireland & Northern Ireland'),
('Carton House - O''Meara', 'Ireland & Northern Ireland'),
('Carya Golf Club', 'Turkey'),
('Castle Stuart Golf Links', 'Scotland'),
('Castlerock - Mussenden', 'Ireland & Northern Ireland'),
('Castro Marim (Atlântico & Grouse)', 'Portugal'),
('Castro Marim (Grouse & Guadiana)', 'Portugal'),
('Castro Marim (Guadiana & Atlântico)', 'Portugal'),
('Celebration Golf Club', 'Orlando / Central Florida'),
('Celtic Manor - Montgomerie', 'Wales'),
('Celtic Manor - Roman Road', 'Wales'),
('Celtic Manor - Twenty Ten', 'Wales'),
('ChampionsGate International', 'Orlando / Central Florida'),
('Chart Hills Golf Club', 'England'),
('Chart Hills Golf Club - The 55', 'England'),
('Chart Hills Golf Club - The 66', 'England'),
('Château des Vigiers (Vallée-Lac)', 'France'),
('Chichester Golf Club - Cathedral', 'England'),
('Chilworth Golf Centre', 'England'),
('China Fleet Country Club', 'England'),
('Chobham Golf Club', 'England'),
('Churston Golf Club', 'England'),
('Clacton-on-Sea Golf Club', 'England'),
('Clandon Golf', 'England'),
('Clandon Regis Golf Club', 'England'),
('Club de Campo La Zagaleta (Old)', 'Spain'),
('Club de Campo Villa de Madrid (Negro)', 'Spain'),
('Club de Golf Alcanada', 'Spain'),
('Club de Golf Barcelona', 'Spain'),
('Clyne Golf Club', 'Wales'),
('Cobtree Manor Golf Club', 'England'),
('Conwy Golf Club', 'Wales'),
('Cooden Beach Golf Club', 'England'),
('Coombe Wood Golf Club', 'England'),
('Cornelia Golf Club King', 'Turkey'),
('Cornelia Golf Club Prince', 'Turkey'),
('Cornelia Golf Club Queen', 'Turkey'),
('Cottesmore Golf Club', 'England'),
('Coulsdon Manor & Golf Club', 'England'),
('County Sligo', 'Ireland & Northern Ireland'),
('Craigielaw Golf Club', 'Scotland'),
('Craigtoun Course (formerly The Duke''s Course)', 'Scotland'),
('Crail Golfing Society - Balcomie', 'Scotland'),
('Crail Golfing Society - Craighead Links', 'Scotland'),
('Crane Valley Golf Club', 'England'),
('Crowborough Beacon Golf Club', 'England'),
('Cruden Bay Golf Club - Main', 'Scotland'),
('Cuckfield Golf Centre', 'England'),
('Cullinan Links Golf Club', 'Turkey'),
('Cullinan Links Golf Club Olympos', 'Turkey'),
('Dalmahoy - East Course', 'Scotland'),
('Dalmahoy - West Course', 'Scotland'),
('Denham Golf Club', 'England'),
('Devon Golf & Country Club', 'England'),
('Dibden Golf Centre', 'England'),
('Dinard Golf', 'France'),
('Disney''s Lake Buena Vista Golf Course', 'Orlando / Central Florida'),
('Disney''s Palm Golf Course', 'Orlando / Central Florida'),
('Dolce CampoReal Lisboa', 'Portugal'),
('Dona Julia', 'Spain'),
('Donnington Grove Golf Course', 'England'),
('Dooks', 'Ireland & Northern Ireland'),
('Dorset Golf and Country Club', 'England'),
('Druids Glen', 'Ireland & Northern Ireland'),
('Druids Heath', 'Ireland & Northern Ireland'),
('Dumbarnie Links', 'Scotland'),
('Dummer Golf Club', 'England'),
('Dunbar Golf Club', 'Scotland'),
('Dundonald Links', 'Scotland'),
('East Horton - Parkland Course', 'England'),
('East Horton - The Greenwood Course', 'England'),
('East Sussex National Hotel & Resort - East', 'England'),
('Easter Moffat Golf Club', 'Scotland'),
('El Bosque', 'Spain'),
('El Paraiso', 'Spain'),
('El Plantio', 'Spain'),
('El Saler', 'Spain'),
('El Valle', 'Spain'),
('Eltham Warren Golf Club', 'England'),
('Emporda Golf Resort (Dunes)', 'Spain'),
('Emporda Golf Resort (Forest)', 'Spain'),
('Enmore Park Golf Club', 'England'),
('Enniscrone', 'Ireland & Northern Ireland'),
('Espiche Golf', 'Portugal'),
('Estela Golf Club', 'Portugal'),
('Estepona Golf', 'Spain'),
('Estoril Golf Club', 'Portugal'),
('Evian', 'France'),
('Exeter Golf and Country Club', 'England'),
('Fairmont St Andrews - Kittocks', 'Scotland'),
('Fairmont St Andrews - Torrance', 'Scotland'),
('Falcon''s Fire Golf Club', 'Orlando / Central Florida'),
('Falmouth Golf Club', 'England'),
('Ferragudo Golf Course', 'Portugal'),
('Finca Cortesin Golf Club', 'Spain'),
('Flamingos', 'Spain'),
('Fleetlands Golf Club', 'England'),
('Font del Llop', 'Spain'),
('Fontainebleau Golf Club', 'France'),
('Forest of Arden - Arden', 'England'),
('Forest of Arden - Aylesford', 'England'),
('Forest Pines - Forest/Pines', 'England'),
('Forfar Golf Club', 'Scotland'),
('Forrester Park Golf Club', 'Scotland'),
('Fota Island', 'Ireland & Northern Ireland'),
('Foxhills Golf Club - Bernard Hunt', 'England'),
('Foxhills Golf Club - Longcross', 'England'),
('Frégate Provence', 'France'),
('Fulwell Golf Club', 'England'),
('Gillingham GC', 'England'),
('Gleneagles - King''s Course', 'Scotland'),
('Gleneagles Golf Club - Queen''s Course', 'England'),
('Gleneagles Golf Resort Queens Course', 'Scotland'),
('Gleneagles PGA Centenary', 'Scotland'),
('Gloria Golf Club New', 'Turkey'),
('Gloria Golf Club Old', 'Turkey'),
('Golf Barrière de Saint-Julien', 'France'),
('Golf Club de Vézac Aurillac', 'France'),
('Golf Costa Adeje', 'Spain'),
('Golf d''Angers', 'France'),
('Golf d''Apremont', 'France'),
('Golf d''Arcachon', 'France'),
('Golf d''Arcangues', 'France'),
('Golf d''Aro', 'Spain'),
('Golf d''Arras (La Vallée)', 'France'),
('Golf d''Etretat', 'France'),
('Golf d''Hardelot (Les Dunes)', 'France'),
('Golf d''Hardelot (Les Pins)', 'France'),
('Golf d''Opio Valbonne', 'France'),
('Golf de Baden', 'France'),
('Golf de Biscarrosse (Forêt-Océan)', 'France'),
('Golf de Cannes-Mougins', 'France'),
('Golf de Cergy', 'France'),
('Golf de Chalon sur Saône', 'France'),
('Golf de Chantilly (Les Longères)', 'France'),
('Golf de Chantilly (Vineuil)', 'France'),
('Golf de Chiberta', 'France'),
('Golf de Dunkerque Grand Littoral (Flandres)', 'France'),
('Golf de Faulquemont-Pontpierre', 'France'),
('Golf de l''Ermitage', 'France'),
('Golf de l''Isle Adam', 'France'),
('Golf de la Bretesche', 'France'),
('Golf de La Forêt de Chantilly', 'France'),
('Golf de la Grande Bastide', 'France'),
('Golf de La Grande Romanie', 'France'),
('Golf de la Grange aux Ormes', 'France'),
('Golf de Marseille la Salette', 'France'),
('Golf de Nancy Aingeray', 'France'),
('Golf de Pléneuf-Val-André', 'France'),
('Golf de Raray (La Licorne)', 'France'),
('Golf de Rochefort', 'France'),
('Golf de Roquebrune Resort', 'France'),
('Golf de Saint-Cast Côte d''Émeraude (Links 1926)', 'France'),
('Golf de Saint-Endréol', 'France'),
('Golf de Saint-Germain (Grand Parcours)', 'France'),
('Golf de Saint-Laurent', 'France'),
('Golf de St-Donat', 'France'),
('Golf de Teynac', 'France'),
('Golf de Valescure', 'France'),
('Golf de Villarceaux', 'France'),
('Golf de Wimereux', 'France'),
('Golf del Sur', 'Spain'),
('Golf des Ormes', 'France'),
('Golf des Yvelines (Les Chênes)', 'France'),
('Golf du Château de Cély', 'France'),
('Golf du Touquet (La Forêt)', 'France'),
('Golf International Barrière La Baule (Diane Barrière-Desseigne)', 'France'),
('Golf International Barrière La Baule (Lucien Barrière)', 'France'),
('Golf International de Grenoble', 'France'),
('Golf Las Americas', 'Spain'),
('Golf Santander', 'Spain'),
('Golspie Golf Club', 'Scotland'),
('Gosfield Lake Golf Club - Lakes', 'England'),
('Gosfield Lake Golf Club - Meadows', 'England'),
('Grand Saint-Émilionnais', 'France'),
('Granville Golf Club (Links)', 'France'),
('Guardian Bom Sucesso Golf', 'Portugal'),
('Guildford Golf Club', 'England'),
('Gullane - No. 1', 'Scotland'),
('Gullane - No. 2', 'Scotland'),
('Gullane - No. 3', 'Scotland'),
('Hacienda del Alamo', 'Spain'),
('Hacienda Riquelme Golf Resort', 'Spain'),
('Ham Manor Golf Club', 'England'),
('Hankley Common Golf Club', 'England'),
('Harleyford Golf Club', 'England'),
('Hartley Wintney Golf Club', 'England'),
('Hawk''s Landing Golf Club', 'Orlando / Central Florida'),
('Hayling Golf Club', 'England'),
('Hayston Golf Club', 'Scotland'),
('Haywards Heath Golf Club', 'England'),
('Hever Castle Golf Club - Championship', 'England'),
('Hever Castle Golf Club - Championship Red Rated Course', 'England'),
('Heythrop Park Resort', 'England'),
('Highcliffe Castle Golf Club', 'England'),
('Hill Valley - Emerald', 'England'),
('Hill Valley - Sapphire', 'England'),
('Hoebridge Golf Centre', 'England'),
('Holsworthy Golf Club', 'England'),
('Hossegor', 'France'),
('Hurtmore Golf Club', 'England'),
('Ifield Golf Club', 'England')
ON CONFLICT (name) DO UPDATE SET region = EXCLUDED.region;

INSERT INTO courses (name, region) VALUES
('Ilford Golf Club', 'England'),
('Infinitum Resort (Hills)', 'Spain'),
('Infinitum Resort (Lakes)', 'Spain'),
('Isle of Purbeck Golf Club', 'England'),
('Isle of Wedmore Golf Club', 'England'),
('Jameson Golf Links', 'Ireland & Northern Ireland'),
('Kaya Palazzo Golf Resort', 'Turkey'),
('Kilmarnock (Barassie) - Barassie Links', 'Scotland'),
('Kilspindie Golf Club', 'Scotland'),
('Kings Hill Golf Club', 'England'),
('Kingsbarns Golf Links', 'Scotland'),
('Kingswood Golf & Country Club', 'England'),
('Knighton Heath Golf Club', 'England'),
('La Cala Resort - Campo America', 'Spain'),
('La Cala Resort - Campo Asia', 'Spain'),
('La Cala Resort - Campo Europa', 'Spain'),
('La Finca Golf (Algorfa)', 'Spain'),
('La Galiana', 'Spain'),
('La Hacienda Links Golf Resort (Links)', 'Spain'),
('La Manga Club - North Course', 'Spain'),
('La Manga Club - West Course', 'Spain'),
('La Reserva Club', 'Spain'),
('La Torre', 'Spain'),
('Ladybank Golf Club', 'Scotland'),
('LaFinca Golf (Madrid)', 'Spain'),
('Lahinch - Old', 'Ireland & Northern Ireland'),
('Langland Bay Golf Club', 'Wales'),
('Langley Park Golf Club', 'England'),
('Lanhydrock Hotel and Golf Club', 'England'),
('Larrabea Golf Club', 'Spain'),
('Las Colinas Golf & Country Club', 'Spain'),
('Las Ramblas', 'Spain'),
('Launceston Golf Club', 'England'),
('Lauro Golf', 'Spain'),
('Le Frégate Provence Golf & CC (Frégate)', 'France'),
('Le Golf National (Aigle)', 'France'),
('Le Golf National (Albatros)', 'France'),
('Le Touquet Golf Resort (La Mer)', 'France'),
('Leatherhead Golf Club', 'England'),
('Lee-On-The-Solent Golf Club', 'England'),
('Leeds Castle Golf Course', 'England'),
('Leven Links', 'Scotland'),
('Limère', 'France'),
('Lingfield Park Golf Club', 'England'),
('Linlithgow Golf Club', 'Scotland'),
('Lo Romero Golf', 'Spain'),
('Longniddry Golf Club', 'Scotland'),
('Looe Golf Club', 'England'),
('Los Naranjos Golf Club', 'Spain'),
('Lough Erne - Faldo', 'Ireland & Northern Ireland'),
('Lullingstone Park Golf Course - Park Course', 'England'),
('Lullingstone Park Golf Course - Valley Course', 'England'),
('Lundin Golf Club', 'Scotland'),
('Lydd Golf Club', 'England'),
('Lykia Links Antalya', 'Turkey'),
('Lyme Regis Golf Club', 'England'),
('Lys Chantilly (Les Chênes)', 'France'),
('Machrihanish Dunes Golf Course', 'Scotland'),
('Machrihanish Golf Club - Championship', 'Scotland'),
('Maidenhead Golf Club', 'England'),
('Maioris', 'Spain'),
('Maison Blanche (Les Sources)', 'France'),
('Malone', 'Ireland & Northern Ireland'),
('Mannings Heath Golf Club - The Kingfisher Course', 'England'),
('Mar Menor', 'Spain'),
('Marbella Club Golf Resort', 'Spain'),
('Marbella Golf & Country Club', 'Spain'),
('Maspalomas', 'Spain'),
('Melia Villaitana - Levante', 'Spain'),
('Melia Villaitana - Poniente', 'Spain'),
('Meloneras', 'Spain'),
('Mendip Golf Club', 'England'),
('Meon Valley Marriott Hotel & Country Club', 'England'),
('Merrist Wood Golf Club', 'England'),
('MetroWest Golf Club', 'Orlando / Central Florida'),
('Meyrick Park Golf Club', 'England'),
('Mid Sussex Golf Club', 'England'),
('Mijas Golf - Los Olivos', 'Spain'),
('Mijas Golf (Los Lagos)', 'Spain'),
('Milford Golf Club', 'England'),
('Milngavie Golf Club', 'Scotland'),
('Minehead and West Somerset Golf Club', 'England'),
('Mission Resort El Campeón', 'Orlando / Central Florida'),
('Mission Resort Las Colinas', 'Orlando / Central Florida'),
('Moliets (Forêt & Océan)', 'France'),
('Monifieth Golf Links - Medal', 'Scotland'),
('Montado Hotel & Golf Resort', 'Portugal'),
('Monte Rei Golf & Country Club', 'Portugal'),
('Montecastillo Golf Resort', 'Spain'),
('Montrose Golf Links - 1562 Medal', 'Scotland'),
('Montrose Golf Links - Broomfield Course', 'Scotland'),
('Morfontaine (Grand Parcours)', 'France'),
('Morgado Golf Course', 'Portugal'),
('Muirfield', 'Scotland'),
('Mullion Golf Club', 'England'),
('Murcar Links - Championship', 'Scotland'),
('Murrayfield Golf Club', 'Scotland'),
('Mystic Dunes Golf Club', 'Orlando / Central Florida'),
('Nairn Dunbar Golf Club', 'Scotland'),
('Nairn Golf Club - Championship', 'Scotland'),
('Nampont Saint-Martin (Le Belvédère)', 'France'),
('Nampont Saint-Martin (Les Cygnes)', 'France'),
('National Golf Club', 'Turkey'),
('Nefyn & District - Championship', 'Wales'),
('Nevill Golf Club', 'England'),
('Newbury & Crookham Golf Club', 'England'),
('Newmachar Golf Club - Hawkshill', 'Scotland'),
('Newquay Golf Club', 'England'),
('Nizels Golf Club', 'England'),
('North Berwick - West Links', 'Scotland'),
('North Foreland Golf Club - Main Course', 'England'),
('North Oxford Golf Club', 'England'),
('Oitavos Dunes', 'Portugal'),
('Old Course Ranfurly Golf Club', 'Scotland'),
('Old Head', 'Ireland & Northern Ireland'),
('Omaha Beach Golf (De Gaulle)', 'France'),
('Omaha Beach Golf (The Churchill Tour Course)', 'France'),
('Omaha Beach Golf (The Eisenhower)', 'France'),
('Onyria Quinta da Marinha', 'Portugal'),
('Oporto Golf Club', 'Portugal'),
('Orange County National Crooked Cat', 'Orlando / Central Florida'),
('Orange County National Panther Lake', 'Orlando / Central Florida'),
('Orchardleigh Golf Club', 'England'),
('Orsett Golf Club', 'England'),
('Osborne Golf Club', 'England'),
('Oulton Hall - 1-9/19-27', 'England'),
('Palheiro Golf', 'Portugal'),
('Palmares (Alvor & Lagos)', 'Portugal'),
('Palmares (Lagos & Praia)', 'Portugal'),
('Palmares (Praia & Alvor)', 'Portugal'),
('Panmure Golf Club', 'Scotland'),
('Parador de Málaga', 'Spain'),
('Paris International', 'France'),
('Parley Golf Centre', 'England'),
('Penha Longa Resort (Atlântico)', 'Portugal'),
('Penina Championship', 'Portugal'),
('Pennard Golf Club', 'Wales'),
('Peralada', 'Spain'),
('Perranporth Golf Club', 'England'),
('Pestana Alto Golf', 'Portugal'),
('Pestana Gramacho', 'Portugal'),
('Pestana Silves Golf', 'Portugal'),
('Pestana Vale da Pinta', 'Portugal'),
('Pestana Vila Sol (Challenge & Prestige)', 'Portugal'),
('Pestana Vila Sol (Prestige & Prime)', 'Portugal'),
('Pestana Vila Sol (Prime & Challenge)', 'Portugal'),
('Piltdown Golf Club', 'England'),
('Pine Cliffs Golf Course', 'Portugal'),
('Porthmadog Golf Club', 'Wales'),
('Porthpean Golf Club', 'England'),
('Portmarnock Golf Club', 'Ireland & Northern Ireland'),
('Porto Santo Golfe', 'Portugal'),
('Portstewart - Strand', 'Ireland & Northern Ireland'),
('Poult Wood Golf Course', 'England'),
('Powfoot Golf Club', 'Scotland'),
('Prestwick Golf Club', 'Scotland'),
('Prince''s Golf Club - Shore & Dunes', 'England'),
('Providence Golf Club', 'Orlando / Central Florida'),
('Pula Golf', 'Spain'),
('Puttenham Golf Club', 'England'),
('Pyecombe Golf Course', 'England'),
('Pyrford Golf Club', 'England'),
('Quinta da Ria', 'Portugal'),
('Quinta de Cima', 'Portugal'),
('Quinta do Lago (Laranjal)', 'Portugal'),
('Quinta do Lago (North)', 'Portugal'),
('Quinta do Lago (South)', 'Portugal'),
('Quinta do Peru', 'Portugal'),
('Quinta do Vale', 'Portugal'),
('Real Club de Golf de La Coruña', 'Spain'),
('Real Club de Golf La Herreria', 'Spain'),
('Real Club de Golf Las Brisas', 'Spain'),
('Real Club de Golf Sotogrande', 'Spain'),
('Real Club La Moraleja (1)', 'Spain'),
('Real Club La Moraleja (2)', 'Spain'),
('Real Club La Moraleja (3)', 'Spain'),
('Real Club La Moraleja (4)', 'Spain'),
('Real Club Pedreña', 'Spain'),
('Real Club Pineda de Sevilla', 'Spain'),
('Real Club Sevilla Golf', 'Spain'),
('Real Club Valderrama', 'Spain'),
('Real El Prat (Pink)', 'Spain'),
('Real El Prat (Yellow)', 'Spain'),
('Real La Manga Club (South)', 'Spain'),
('Real Puerta de Hierro (Abajo)', 'Spain'),
('Real Puerta de Hierro (Arriba)', 'Spain'),
('Real Sociedad de Golf de Neguri', 'Spain'),
('Real Sociedad Hipica Espanola (North)', 'Spain'),
('Real Sociedad Hipica Espanola (South)', 'Spain'),
('Redlibbets Golf Club', 'England'),
('Remedy Oak Golf Club', 'England'),
('Reunion Resort Nicklaus', 'Orlando / Central Florida'),
('Reunion Resort Palmer', 'Orlando / Central Florida'),
('Reunion Resort Watson', 'Orlando / Central Florida'),
('Ribagolfe Lakes', 'Portugal'),
('Ribagolfe Oaks', 'Portugal'),
('Robinson Nobilis Golf Club', 'Turkey'),
('Rochester & Cobham Park Golf Club', 'England'),
('Roda', 'Spain'),
('Rolls of Monmouth Golf Club', 'Wales'),
('Rookwood Golf Course', 'England'),
('Rosapenna - Old Tom Morris', 'Ireland & Northern Ireland'),
('Rosapenna - Sandy Hills', 'Ireland & Northern Ireland'),
('Rosapenna - St Patrick''s Links', 'Ireland & Northern Ireland'),
('Royal Aberdeen - Balgownie', 'Scotland'),
('Royal Belfast', 'Ireland & Northern Ireland'),
('Royal Birkdale Golf Club', 'England'),
('Royal County Down', 'Ireland & Northern Ireland'),
('Royal Dornoch - Championship', 'Scotland'),
('Royal Dublin', 'Ireland & Northern Ireland'),
('Royal Eastbourne Golf Club - Devonshire', 'England'),
('Royal Epping Forest Golf Club', 'England'),
('Royal Mid-Surrey Golf Club - JH Taylor Course', 'England'),
('Royal Mougins Golf Resort', 'France'),
('Royal Porthcawl Golf Club', 'Wales'),
('Royal Portrush - Dunluce', 'Ireland & Northern Ireland'),
('Royal Portrush - Valley', 'Ireland & Northern Ireland'),
('Royal St David''s Golf Club', 'Wales'),
('Royal St George''s Golf Club', 'England'),
('Royal Troon - Old Course', 'Scotland'),
('Royal Winchester Golf Club', 'England'),
('Rusper Golf Club', 'England'),
('Rye Hill Golf Club', 'England'),
('Saint-Jean-de-Monts', 'France'),
('Saint-Malo Golf Resort (L''Étang)', 'France'),
('Saint-Nom-la-Bretèche (Bleu)', 'France'),
('Saint-Nom-la-Bretèche (Rouge)', 'France'),
('Salgados Golf Course', 'Portugal'),
('Salobre - New', 'Spain'),
('Salobre - Old', 'Spain'),
('San Lorenzo Golf Course', 'Portugal'),
('San Roque Club (New)', 'Spain'),
('San Roque Club (Old)', 'Spain'),
('Santa Maria', 'Spain'),
('Santana Golf', 'Spain'),
('Santo da Serra', 'Portugal'),
('Santo Estevao', 'Portugal'),
('Scotscraig Golf Club', 'Scotland'),
('Seaford Golf Club', 'England'),
('Seignosse', 'France'),
('Shingle Creek Golf Club', 'Orlando / Central Florida'),
('Silvermere Golf Club', 'England'),
('Sittingbourne & Milton Regis Golf Club', 'England'),
('Skylark Golf & Country Club', 'England'),
('Slaley Hall - Hunting', 'England'),
('Slaley Hall - Priestman', 'England'),
('Slieve Russell', 'Ireland & Northern Ireland'),
('Slinfold Golf & Country Club', 'England'),
('Son Gual Golf', 'Spain'),
('Son Muntaner', 'Spain'),
('Son Quint', 'Spain'),
('Son Servera', 'Spain'),
('Son Vida', 'Spain'),
('Souillac Golf & Country Club', 'France'),
('South Beds Golf Club - Warden Course', 'England'),
('South Winchester Golf Club', 'England'),
('Southern Dunes Golf & Country Club', 'Orlando / Central Florida'),
('Southerndown Golf Club', 'Wales'),
('Southerness Golf Club', 'Scotland'),
('Spérone', 'France'),
('Spey Valley Golf Club', 'Scotland'),
('St Andrews Links - Castle Course', 'Scotland'),
('St Andrews Links - Eden Course', 'Scotland'),
('St Andrews Links - Jubilee Course', 'Scotland'),
('St Andrews Links - New Course', 'Scotland'),
('St Andrews Links - Old Course', 'Scotland'),
('St Andrews Links - Strathtyrum Course', 'Scotland'),
('St Austell Golf Course', 'England'),
('St George''s Hill Golf Club', 'England'),
('St Pierre - Old Course', 'Wales'),
('Stoneham Golf Club', 'England'),
('Strathmore Golf Centre - Rannaleroch', 'Scotland'),
('Sueno Golf Club Dunes', 'Turkey'),
('Sueno Golf Club Pines', 'Turkey'),
('Sunbury Golf Centre', 'England'),
('Sundridge East Course GC', 'England'),
('Sundridge West Course GC', 'England'),
('Surrey Downs Golf Club', 'England'),
('Sutton Green Golf Club', 'England'),
('T Golf Palma', 'Spain'),
('Tehidy Park Golf Club', 'England'),
('Teignmouth Golf Club', 'England'),
('Tenby Golf Club', 'Wales'),
('Terras da Comporta (Dunas)', 'Portugal'),
('Terras da Comporta (Torre)', 'Portugal'),
('Terre Blanche (Château)', 'France'),
('Terre Blanche (Le Riou)', 'France'),
('The Belfry - Brabazon', 'England'),
('The Belfry - Derby', 'England'),
('The Belfry - PGA National', 'England'),
('The Berkshire Golf Club - Blue', 'England'),
('The Drift Golf Club', 'England'),
('The Els Club Vilamoura', 'Portugal'),
('The Glen Golf Club', 'Scotland'),
('The Grove', 'England'),
('The Hertfordshire GC', 'England'),
('The Island', 'Ireland & Northern Ireland'),
('The K Club - Palmer North', 'Ireland & Northern Ireland'),
('The K Club - Palmer South', 'Ireland & Northern Ireland'),
('The Machrie Golf Links', 'Scotland')
ON CONFLICT (name) DO UPDATE SET region = EXCLUDED.region;

INSERT INTO courses (name, region) VALUES
('The Moffat Golf Club', 'Scotland'),
('The Montgomerie Maxx Royal', 'Turkey'),
('The Nottinghamshire - Signature', 'England'),
('The Point at Polzeath', 'England'),
('The Renaissance Club', 'Scotland'),
('The Wiltshire Golf Club', 'England'),
('Thorpe Hall Golf Club', 'England'),
('Tilgate Forest Golf Course', 'England'),
('Torrequebrada', 'Spain'),
('Tramores', 'Spain'),
('Trethorne Golf Club', 'England'),
('Trevose Golf Club', 'England'),
('Troia Resort', 'Portugal'),
('Trump Doonbeg', 'Ireland & Northern Ireland'),
('Trump International Golf Links Scotland', 'Scotland'),
('Trump Turnberry - Ailsa', 'Scotland'),
('Trump Turnberry - King Robert the Bruce', 'Scotland'),
('Tyrrells Wood Golf Club', 'England'),
('Upchurch River Valley Golf Course - North', 'England'),
('Vale do Lobo Ocean', 'Portugal'),
('Vale do Lobo Royal', 'Portugal'),
('Vale Resort - Lake', 'Wales'),
('Vale Resort - Wales National', 'Wales'),
('Vall d''Or', 'Spain'),
('Valle Romano', 'Spain'),
('Vidago Palace Golf Course', 'Portugal'),
('Vilamoura Golf Club - Laguna', 'Portugal'),
('Vilamoura Golf Club - Millennium', 'Portugal'),
('Vilamoura Golf Club - Pinhal', 'Portugal'),
('Vilamoura Golf Club - The Old Course', 'Portugal'),
('Villamartin', 'Spain'),
('Waldorf Astoria Golf Club', 'Orlando / Central Florida'),
('Walton Heath Golf Club - New Course', 'England'),
('Wareham Golf Club', 'England'),
('Waterville', 'Ireland & Northern Ireland'),
('Wellow Golf Club', 'England'),
('West Cornwall Golf Club', 'England'),
('West Hill Golf Club', 'England'),
('West Hove Golf Club', 'England'),
('West Lancashire Golf Club', 'England'),
('West Malling Golf Club - Hurricane', 'England'),
('West Sussex Golf Club', 'England'),
('Westerham Golf Club', 'England'),
('Western Gailes Golf Club', 'Scotland'),
('Westgate and Birchington Golf Club', 'England'),
('Weymouth Golf Club', 'England'),
('Whipsnade Park Golf Club', 'England'),
('Windlesham Golf Club', 'England'),
('Woking Golf Club', 'England'),
('Woldingham Golf Club', 'England'),
('Woodhall Spa - Bracken', 'England'),
('Woodhall Spa - Hotchkin', 'England'),
('Wrotham Heath Golf Club', 'England'),
('Wycombe Heights Golf Centre', 'England'),
('Beaconsfield Golf Club', 'England'),
('Bridport & West Dorset Golf Club', 'England'),
('Broome Manor', 'England'),
('Canterbury Golf Club', 'England'),
('Centurion Golf Club', 'England'),
('Corhampton Golf Club', 'England'),
('Dale Hill Hotel & Golf Club - Woosnam Course', 'England'),
('Darenth Valley Golf Course', 'England'),
('East Sussex National Hotel & Resort - West', 'England'),
('Freshwater Bay Golf Club', 'England'),
('Hanbury Manor Golf & Country Club', 'England'),
('Hindhead Golf Club', 'England'),
('Lamberhurst GC', 'England'),
('Oxford Golf Club', 'England'),
('Pine Ridge Golf Club', 'England'),
('Royal North Devon Golf Club', 'England'),
('Sherborne Golf Club', 'England'),
('Swinley Forest Golf Club', 'England'),
('The Hampshire Golf Club', 'England'),
('The Oxfordshire GC', 'England'),
('Walmer & Kingsdown Golf Club', 'England'),
('Waterlooville Golf Club', 'England'),
('Weald of Kent Golf Club', 'England'),
('Westridge Golf Centre', 'England'),
('Wheathill Golf Club', 'England'),
('Wickham Park Golf Club', 'England'),
('Wildernesse Golf Club', 'England'),
('Army Golf Club', 'England'),
('Betchworth Park Golf Club', 'England'),
('Bird Hills Golf Centre', 'England'),
('Chartham Park Golf Club', 'England'),
('Chestfield Golf Club', 'England'),
('Chichester Golf Club - Tower', 'England'),
('Copthorne Golf Club', 'England'),
('Dunstable Downs Golf Club', 'England'),
('Faversham Golf Club', 'England'),
('Furzeley Golf Club', 'England'),
('Gleneagles Golf Club Kings Course', 'England'),
('Hadden Hill Golf Club', 'England'),
('Hampton Court Palace Golf Club', 'England'),
('Hill Barn Golf Club', 'England'),
('Okehampton Golf Club', 'England'),
('Park Wood Golf Club', 'England'),
('Pedham Place Golf Centre', 'England'),
('Purley Downs Golf Club', 'England'),
('Salisbury & South Wilts Golf Club', 'England'),
('Sweetwoods Park Golf Club', 'England'),
('The Ridge Golf Club', 'England'),
('Theale Golf Club', 'England'),
('Worthing Golf Club - Colt Course', 'England'),
('Chelsfield Lakes Golf Club', 'England'),
('Eastbourne Downs Golf Club', 'England'),
('Goodwood - Downs', 'England'),
('London Club International GC', 'England'),
('Mid Kent GC', 'England'),
('Prince''s Golf Club - Dunes & Himalyas', 'England'),
('Surrey National Golf Club', 'England'),
('Ashford (Kent) Golf Club', 'England'),
('Boundary Lakes Golf Course', 'England'),
('Farleigh Golf Club', 'England'),
('Knole Park Golf Club', 'England'),
('Portsmouth Golf Course', 'England'),
('Shrivenham Park Golf Club', 'England'),
('The Dalaman Golf Club', 'Turkey'),
('The Palmerston Course GC', 'England'),
('Woburn Golf Club - The Duchess', 'England'),
('Woburn Golf Club - The Duke', 'England'),
('Bearsted Golf Club', 'England'),
('Brocket Hall - Melbourne Course', 'England'),
('Buckingham Golf Club', 'England'),
('Liphook Golf Club', 'England'),
('London Club Heritage GC', 'England'),
('The South Buckinghamshire', 'England'),
('Woburn Golf Club - Marquess Course', 'England'),
('Surbiton Golf Club', 'England'),
('Tandridge Golf Club', 'England'),
('West Cliffs', 'Portugal'),
('Royal Ascot Golf Club', 'England'),
('Littlehampton Golf Club', 'England')
ON CONFLICT (name) DO UPDATE SET region = EXCLUDED.region;
